/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devsmart_moodb_MooDBWrapper */

#ifndef _Included_com_devsmart_moodb_MooDBWrapper
#define _Included_com_devsmart_moodb_MooDBWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devsmart_moodb_MooDBWrapper
 * Method:    moodbopen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_devsmart_moodb_MooDBWrapper_moodbopen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_devsmart_moodb_MooDBWrapper
 * Method:    moodbclose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_devsmart_moodb_MooDBWrapper_moodbclose
  (JNIEnv *, jobject);

/*
 * Class:     com_devsmart_moodb_MooDBWrapper
 * Method:    putObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_devsmart_moodb_MooDBWrapper_putObject
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_devsmart_moodb_MooDBWrapper
 * Method:    putView
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_devsmart_moodb_MooDBWrapper_putView
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_devsmart_moodb_MooDBWrapper
 * Method:    query
 * Signature: (Ljava/lang/String;)Lcom/devsmart/moodb/MooDBWrapper/MooDBCursor;
 */
JNIEXPORT jobject JNICALL Java_com_devsmart_moodb_MooDBWrapper_query
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
