/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devsmart_moodb_MooDBCursor */

#ifndef _Included_com_devsmart_moodb_MooDBCursor
#define _Included_com_devsmart_moodb_MooDBCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devsmart_moodb_MooDBCursor
 * Method:    cursorclose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_devsmart_moodb_MooDBCursor_cursorclose
  (JNIEnv *, jobject);

/*
 * Class:     com_devsmart_moodb_MooDBCursor
 * Method:    next
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_devsmart_moodb_MooDBCursor_next
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
